# Référentiel de fingerprinting WAF/CDN et technologies.
#
# Règle d'honnêteté : on ne retient que des preuves qu'un WAF/CDN est dans le chemin des requêtes.
# Chaque fournisseur est évalué sur ces signaux, jamais sur un nom de vendeur en sous-chaîne libre :
#   headers         noms d'en-têtes de réponse exacts (minuscules)
#   header_prefixes préfixes de noms d'en-têtes (ex. x-akamai-*)
#   header_values   {en-tête: [jetons]} ; le jeton doit être un MOT ENTIER dans la valeur (Server: gws)
#   cookies         préfixes de noms de cookies (ex. visid_incap_123456)
#   cookie_regex    motifs de noms de cookies, comparés en entier (ex. TS + hexadécimal pour F5 ASM)
#   body            marqueurs SPÉCIFIQUES de pages d'erreur du produit ; jamais un simple nom de vendeur
#   cname           domaines précis du CDN dans le CNAME du site : le signal le plus fiable
#   aliases         noms sous lesquels wafw00f désigne ce fournisseur (pour dédoublonner)
# Ni l'émetteur du certificat, ni le PTR, ni les serveurs de noms : ils décrivent l'hébergeur, le
# DNS ou la PKI. Héberger chez AWS, OVH ou Google ne signifie pas avoir un WAF.
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "header_values": {"server": ["cloudflare"]},
        "cookies": ["__cf_bm", "__cfduid", "_cfuvid", "cf_clearance"],
        "body": ["cloudflare ray id"],
        "cname": ["cloudflare.net", "cloudflare.com"],
        "aliases": ["cloudflare"],
    },
    "Akamai": {
        "headers": ["akamai-origin-hop", "x-akamai-request-id"],
        "header_prefixes": ["x-akamai-"],
        "header_values": {"server": ["akamaighost", "akamainetstorage"]},
        "cookies": ["ak_bmsc", "bm_sz", "_abck"],
        "body": ["akamaighost"],
        "cname": ["akamai", "akamaiedge.net", "akamaized.net", "akamaihd.net", "edgekey.net", "edgesuite.net"],
        "aliases": ["akamai"],
    },
    "Fastly": {
        "headers": ["x-fastly-request-id", "x-timer"],
        "cookies": ["_fastly_session"],
        "body": ["fastly error: unknown domain"],
        "cname": ["fastly.net", "fastlylb.net", "fastly"],
        "aliases": ["fastly"],
    },
    "Varnish": {  # cache HTTP : affiché, sans bonus
        "headers": ["x-varnish"],
        "header_values": {"via": ["varnish"]},
        "body": ["varnish cache server"],
        "aliases": ["varnish"],
    },
    "Amazon CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "header_values": {"via": ["cloudfront"], "server": ["cloudfront"]},
        "body": ["generated by cloudfront"],
        "cname": ["cloudfront.net"],
        "aliases": ["cloudfront"],
    },
    "Google Front End": {
        "headers": ["x-guploader-uploadid"],
        "header_values": {"server": ["gws", "esf", "google frontend"]},
        "cname": ["googlehosted.com", "googleusercontent.com", "ghs.google.com"],
        "aliases": ["google front end", "google frontend"],
    },
    "Imperva": {
        "headers": ["x-iinfo"],
        "header_values": {"x-cdn": ["imperva", "incapsula"]},
        "cookies": ["visid_incap", "incap_ses", "nlbi_"],
        "body": ["incapsula incident id", "powered by incapsula"],
        "cname": ["incapdns.net", "impervadns.net"],
        "aliases": ["imperva", "incapsula"],
    },
    "Azure Front Door": {
        "headers": ["x-azure-ref", "x-fd-features"],
        "cname": ["azurefd.net", "azureedge.net"],
        "aliases": ["azure front door"],
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info", "x-cshm"],
        "header_values": {"server": ["bigip", "big-ip"]},
        "cookies": ["bigipserver", "f5_cspm", "mrhint"],
        "cookie_regex": [r"ts[0-9a-f]{6,}"],  # cookies F5 ASM : TS01918e36, TS24ded377027...
        "body": ["f5_cspm"],
        "cname": ["f5edge", "silverline"],
        "aliases": ["big-ip", "bigip", "f5"],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "header_values": {"server": ["sucuri"]},
        "cookies": ["sucuri_cloudproxy_uuid"],
        "body": ["sucuri cloudproxy", "access denied - sucuri website firewall"],
        "cname": ["sucuri.net"],
        "aliases": ["sucuri"],
    },
    "ModSecurity": {
        "header_values": {"server": ["mod_security", "modsecurity"]},
        "body": ["generated by mod_security"],
        "aliases": ["modsecurity"],
    },
    "DDoS-Guard": {
        "header_values": {"server": ["ddos-guard"]},
        "cookies": ["__ddg"],
        "body": ["ddos-guard"],
        "cname": ["ddos-guard.net"],
        "aliases": ["ddos-guard"],
    },
    "StackPath": {
        "header_prefixes": ["x-stackpath", "x-sp-"],
        "cname": ["stackpathdns.com", "stackpathcdn.com", "stackpath.net"],
        "aliases": ["stackpath"],
    },
    "Zscaler": {
        "header_values": {"server": ["zscaler"]},
        "cookies": ["zscaler"],
        "cname": ["zscaler.net", "zscalerone.net", "zscalertwo.net", "zscloud.net"],
        "aliases": ["zscaler"],
    },
    "Vercel": {
        "headers": ["x-vercel-id", "x-vercel-cache"],
        "header_values": {"server": ["vercel"]},
        "cname": ["vercel-dns.com", "vercel.app"],
        "aliases": ["vercel"],
    },
    "Netlify": {
        "headers": ["x-nf-request-id"],
        "header_values": {"server": ["netlify"]},
        "cname": ["netlify.app", "netlify.com"],
        "aliases": ["netlify"],
    },
    "Heroku": {  # routeur de la plateforme : affiché, sans bonus
        "header_values": {"via": ["vegur"]},
        "cname": ["herokuapp.com", "herokudns.com"],
        "aliases": ["heroku"],
    },
    "Shopify": {  # plateforme e-commerce : affichée, sans bonus
        "header_prefixes": ["x-shopify-"],
        "cookies": ["_shopify"],
        "cname": ["myshopify.com"],
        "aliases": ["shopify"],
    },
}

# Couches détectées mais qui ne sont pas des WAF/CDN : elles sont affichées, jamais comptées dans le
# bonus infrastructure (cache, routeur de plateforme, répartiteur de charge).
NON_PROTECTIVE_LAYERS = {"Varnish", "Heroku", "Shopify", "AWS Elastic Load Balancer"}

# Technologies : uniquement des signaux réels, jamais devinés.
#   server / x-powered-by : jeton en MOT ENTIER dans la valeur de l'en-tête
#   headers               noms d'en-têtes exacts
#   cookies               préfixes de noms de cookies
TECH_SIGNATURES = {
    "Nginx": {"server": ["nginx"]},
    "Apache": {"server": ["apache"]},
    "LiteSpeed": {"server": ["litespeed"]},
    "Caddy": {"server": ["caddy"]},
    "IIS": {"server": ["microsoft-iis"]},
    "PHP": {"x-powered-by": ["php"], "cookies": ["phpsessid"]},
    "ASP.NET": {"x-powered-by": ["asp.net"], "headers": ["x-aspnet-version", "x-aspnetmvc-version"],
                "cookies": ["asp.net_sessionid"]},
    "Java": {"server": ["tomcat", "jetty", "coyote"], "x-powered-by": ["servlet", "jsp"], "cookies": ["jsessionid"]},
    "Node.js": {"x-powered-by": ["express"], "cookies": ["connect.sid"]},
    "Python": {"server": ["gunicorn", "uvicorn", "hypercorn", "granian", "waitress", "werkzeug"],
               "x-powered-by": ["django", "flask"]},
}

SECURITY_HEADERS = {
    "Strict-Transport-Security": "HSTS",
    "Content-Security-Policy": "CSP",
    "X-Frame-Options": "Anti-Clickjacking",
    "X-Content-Type-Options": "Anti-Mime",
    "Referrer-Policy": "Referrer",
    "Permissions-Policy": "Permissions"
}
